### ISSUE TITLE
Potential Borough regression?

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data-postalcode-gb#9]
After running some acceptance tests today I detected a potential regression.

In the past, a Pelias query for `EN52LP` returned `"borough": "Barnet"`:
- https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb/blob/master/data/454/553/645/454553645.geojson
- https://github.com/whosonfirst-data/whosonfirst-data-admin-gb/blob/master/data/115/885/728/5/1158857285.geojson

In the latest builds we're not seeing that association because `borough` is not included in the `wof:hierarchy`.
I did a spot check of the geometry and it appears to intersect:

<img width="527" alt="Screenshot 2022-09-16 at 15 00 35" src="https://user-images.githubusercontent.com/738069/190645360-69fb1f82-86c1-4978-a31d-2b0b9bd00246.png">

I'm not sure what's happened exactly, @tomtaylor is it possible that the `borough` layer wasn't included in the point-in-polygon work?

**Comment by missinglink** [comment]
Two other postcodes from that test suite which have the same issue are `NW74LS` (missing `Barnet`) and `E81DN` (missing `Hackney`).

**Comment by tomtaylor** [comment]
Interesting! That's quite possible. I'll have a look.

**Comment by tomtaylor** [comment]
I think the answer to this is that `postalcode` isn't parented by `borough` in the WOF hierarchy. It can be parented by `locality`, `localadmin` and `region`. So the code that's pulling the hierarchy is actually following the rules here. 

I think that's actually true in the UK's case - there's nothing forcing a postcode to sit inside a borough boundary - many of them probably do straddle multiple boroughs.

https://github.com/whosonfirst/whosonfirst-placetypes

**Comment by missinglink** [comment]
Oh interesting, I noticed a diff from the previous version but it seems that this version is technically correct whereas the previous versions were not 🤔

**Comment by tomtaylor** [comment]
> Oh interesting, I noticed a diff from the previous version but it seems that this version is technically correct whereas the previous versions were not 🤔

Phew!
